import { Inter } from "next/font/google";
import Head from 'next/head';
import "./styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={`${inter.className} bg-white text-black`}>
        <div className="min-h-screen flex flex-col">
          <header className="bg-gray-100 py-4">
            {/* Header content */}
          </header>
          <main className="flex-grow">{children}</main>
          <footer className="bg-gray-100 py-4">
            {/* Footer content */}
          </footer>
        </div>
      </div>
    </>
  );
}

export default RootLayout;